# -- judge.toml --
# 这个文件负责告诉评测姬你需要怎么评测你的程序

# 我们的评测标识符是 pascal_lex
[jobs.pascal_lex]

# 使用 Dockerfile 来源，路径就是当前文件夹，镜像名称是 my-pascal-lexer
image = { source = "dockerfile", path = ".", tag = "my-pascal-lexer" }

# 假如你用的是 Java
run = [
  # 运行程序
  "java Main $input",
]